# Generated by Django 3.2.12 on 2022-04-19 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_path',
            field=models.ImageField(upload_to='WebEnglish/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
