# Generated by Django 3.2.12 on 2022-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishSystem', '0004_auto_20220430_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='html',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
