# Generated by Django 3.2.12 on 2022-05-01 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishSystem', '0005_alter_paragraph_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='html',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
