# Generated by Django 3.2.12 on 2022-05-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishSystem', '0006_auto_20220501_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paragraph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnglishSystem.paragraph'),
        ),
    ]
