# Generated by Django 3.2.12 on 2022-05-12 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishSystem', '0010_paragraph_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
