# Generated by Django 3.2.12 on 2022-03-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebEnglish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingComprehension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentreading', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reading_comprehension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebEnglish.readingcomprehension')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebEnglish.multiplechoice')),
            ],
        ),
    ]
