# Generated by Django 3.2.12 on 2022-03-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebEnglish', '0002_answers_multiplechoice_readingcomprehension'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebEnglish.category'),
        ),
    ]
