# Generated by Django 3.2.12 on 2022-03-06 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebEnglish', '0006_alter_multiplechoice_reading_comprehension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='WebEnglish.multiplechoice'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multipleChoice', to='WebEnglish.category'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='reading_comprehension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipleChoice', to='WebEnglish.readingcomprehension'),
        ),
    ]
