# Generated by Django 3.2.12 on 2022-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEnglish', '0007_auto_20220306_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='answer_correct',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
